version: "3.9"

services: 

  postgres:
    container_name: postgres_container
    image: postgres:12.8
    environment:
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - rd_postgres_volume:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports: 
      - "81:80"
    volumes:
      - rd_pgadmin_volume:/var/lib/pgadmin
    depends_on: 
      - postgres
  
  redis:
    container_name: redis_container
    image: redislabs/rejson:latest
    ports:
      - "6379:6379"

volumes: 
  rd_postgres_volume:
  rd_pgadmin_volume:
